---
- name: Add Vector repository key
  ansible.builtin.apt_key:
    url: https://packages.timber.io/vector/0.38.0/vector-0.38.0-aptly_repo-keyring.gpg
    state: present
  when: ansible_os_family == "Debian"

- name: Add Vector repository
  ansible.builtin.apt_repository:
    repo: "deb https://packages.timber.io/vector/0.38.0/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} main"
    state: present
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: Install Vector
  ansible.builtin.package:
    name: vector
    state: present
